spring:
  application:
    name: skillresume
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
springdoc:
  paths-to-match:
    - /api/**/vi
  swagger-ui:
    use-root-path: true

